language: java
jdk: openjdk13

# The trusty build environment allows for more memory, see https://docs.travis-ci.com/user/reference/overview/
dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx6g"
  matrix:
    - TEST=RunRuhrgebietScenarioTest#prepareConfig
    - TEST=RunRuhrgebietScenarioTest#runScenarioOneIteration
    - TEST=RunRuhrgebietScenarioTest#runScenario20Iterations



script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
